spring.application.name=user-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/user-management-api-db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiry=3600000